%% This file is autogenerated ...

%% This file contains virtual vehicle configuration information.

%% This file is saved at time 15-Feb-2025 15:56:44
                     ConfigInfos.Version = '24.2.0.2833386 (R2024b) Update 4';
                   ConfigInfos.SessionID = 'ConfiguredVirtualVehicle.m';
                   ConfigInfos.LicStatus = [1,1,1,1,1,1,1,1,1];
                ConfigInfos.ProjPathText = 'C:\Users\user\MATLAB\Projects\examples';
                    ConfigInfos.ProjPath = 'C:\Users\user\MATLAB\Projects\examples\VirtualVehicle1\VirtualVehicle';
                 ConfigInfos.SessionName = 'ConfiguredVirtualVehicle';
                 ConfigInfos.XmlPathText = 'C:\Users\user\MATLAB\Projects\examples\VVCCustomCatalog.xml';
               ConfigInfos.TemplateModel = 'VirtualVehicleTemplateArchitecture';
          ConfigInfos.TemplatePlantModel = 'SimulinkPlantModelsArchitecture';
                 ConfigInfos.ConfigModel = 'ConfiguredVirtualVehicleModel';
            ConfigInfos.ConfigPlantModel = 'ConfiguredSimulinkPlantModel';
                    ConfigInfos.VehClass = 'Passenger Vehicle';
                     ConfigInfos.VehArct = 'Electric Vehicle 4EM';
                      ConfigInfos.VehDyn = 1;
              ConfigInfos.PlantModelType = 'Simulink';
                  ConfigInfos.VehChassis = 'Vehicle Body 6DOF Longitudinal and Lateral';
%% Vehicle Configuration
ConfigInfos.FeatureVariantSelectedMap=containers.Map;
ConfigInfos.FeatureVariantSelectedMap('Active Differential Control') = 'No Control';
ConfigInfos.FeatureVariantSelectedMap('Axle Interconnect') = 'No Interconnect';
ConfigInfos.FeatureVariantSelectedMap('Battery Management System') = 'Battery Management System';
ConfigInfos.FeatureVariantSelectedMap('Body and Frame') = 'Vehicle Body 6DOF Longitudinal and Lateral';
ConfigInfos.FeatureVariantSelectedMap('Brake Control Unit') = 'Open Loop';
ConfigInfos.FeatureVariantSelectedMap('Brake System') = 'Brake System';
ConfigInfos.FeatureVariantSelectedMap('DC-DC Converter') = 'DC-DC Converter';
ConfigInfos.FeatureVariantSelectedMap('Drive Shaft Torque Routing') = 'Four Actuator AWD';
ConfigInfos.FeatureVariantSelectedMap('Driver') = 'Predictive Driver';
ConfigInfos.FeatureVariantSelectedMap('Drivetrain') = 'All Wheel Driven by 4EM';
ConfigInfos.FeatureVariantSelectedMap('Drivetrain Wheel Speed Route') = 'Bus';
ConfigInfos.FeatureVariantSelectedMap('Electric Machine 1') = 'Electric Vehicle 4EM - Mapped Motor';
ConfigInfos.FeatureVariantSelectedMap('Electric Machine 2') = 'Electric Vehicle 4EM - Mapped Motor';
ConfigInfos.FeatureVariantSelectedMap('Electric Machine 3') = 'Electric Vehicle 4EM - Mapped Motor';
ConfigInfos.FeatureVariantSelectedMap('Electric Machine 4') = 'Electric Vehicle 4EM - Mapped Motor';
ConfigInfos.FeatureVariantSelectedMap('Electric Motors') = '4EM';
ConfigInfos.FeatureVariantSelectedMap('Energy Storage') = 'Mapped Battery (Electric Vehicle 4EM)';
ConfigInfos.FeatureVariantSelectedMap('Engine') = 'No Engine';
ConfigInfos.FeatureVariantSelectedMap('Engine Control Unit') = 'No Engine Controller';
ConfigInfos.FeatureVariantSelectedMap('Environment') = 'Ambient Conditions';
ConfigInfos.FeatureVariantSelectedMap('Final Drive') = 'Final Drive';
ConfigInfos.FeatureVariantSelectedMap('Front Axle Compliances') = 'Axle Compliances';
ConfigInfos.FeatureVariantSelectedMap('Front Brake Type') = 'Disc';
ConfigInfos.FeatureVariantSelectedMap('Front Differential System') = 'Dual EM Drive Front';
ConfigInfos.FeatureVariantSelectedMap('Front Suspension') = 'Kinematics and Compliance Independent Suspension Front';
ConfigInfos.FeatureVariantSelectedMap('Front Tire Data') = 'Light passenger car 205/60R15';
ConfigInfos.FeatureVariantSelectedMap('Front Tire and Wheel') = 'MF Tires Longitudinal and Lateral Front';
ConfigInfos.FeatureVariantSelectedMap('Hitch') = 'Hitch 6DOF';
ConfigInfos.FeatureVariantSelectedMap('Power Generation') = 'Power Generation';
ConfigInfos.FeatureVariantSelectedMap('Powertrain') = 'Electric Vehicle 4EM';
ConfigInfos.FeatureVariantSelectedMap('Rear Axle Compliances') = 'Axle Compliances';
ConfigInfos.FeatureVariantSelectedMap('Rear Brake Type') = 'Disc';
ConfigInfos.FeatureVariantSelectedMap('Rear Differential System') = 'Dual EM Rear 4EM';
ConfigInfos.FeatureVariantSelectedMap('Rear Suspension') = 'Kinematics and Compliance Independent Suspension Rear';
ConfigInfos.FeatureVariantSelectedMap('Rear Tire Data') = 'Light passenger car 205/60R15';
ConfigInfos.FeatureVariantSelectedMap('Rear Tire and Wheel') = 'MF Tires Longitudinal and Lateral Rear';
ConfigInfos.FeatureVariantSelectedMap('Refrigeration Loop') = 'System Level';
ConfigInfos.FeatureVariantSelectedMap('Sensor') = 'IMU Sensor';
ConfigInfos.FeatureVariantSelectedMap('Solver Configuration') = 'Solver Configuration';
ConfigInfos.FeatureVariantSelectedMap('Steering System') = 'Kinematic Steering';
ConfigInfos.FeatureVariantSelectedMap('Suspension System') = 'Suspension System';
ConfigInfos.FeatureVariantSelectedMap('Thermal Control Unit') = 'No Thermal Control';
ConfigInfos.FeatureVariantSelectedMap('Thermal System') = 'Constant Temperature';
ConfigInfos.FeatureVariantSelectedMap('Tire and Wheel System') = 'Tire and Wheel System';
ConfigInfos.FeatureVariantSelectedMap('Trailer') = 'No Trailer';
ConfigInfos.FeatureVariantSelectedMap('Trailer Body') = 'Trailer Body 6DOF';
ConfigInfos.FeatureVariantSelectedMap('Trailer Suspension') = 'Z Force Pass Through 6DOF';
ConfigInfos.FeatureVariantSelectedMap('Trailer Tire') = 'MF Tires Longitudinal and Lateral';
ConfigInfos.FeatureVariantSelectedMap('Transmission') = 'Ideal Fixed Gear Transmission';
ConfigInfos.FeatureVariantSelectedMap('Transmission Control Unit') = 'Driver Pass Through';
ConfigInfos.FeatureVariantSelectedMap('Variant Source') = 'Multi Actuator AWD';
ConfigInfos.FeatureVariantSelectedMap('Vehicle Architecture') = 'Electric Vehicle 4EM';
ConfigInfos.FeatureVariantSelectedMap('Vehicle Control Unit') = 'EV 4EM';

%% User Modified Data
            ConfigInfos.DataModified=[];

%% Test Plan

             ConfigInfos.TestPlan{1}.Num = 1;
          ConfigInfos.TestPlan{1}.Source = 'Scenario.sldd';
            ConfigInfos.TestPlan{1}.Name = 'Increasing Steer';
           ConfigInfos.TestPlan{1}.Cycle = 'Disabled';
          ConfigInfos.TestPlan{1}.Driver = 'Predictive Driver';
        ConfigInfos.TestPlan{1}.Data=[];

             ConfigInfos.TestPlan{2}.Num = 2;
          ConfigInfos.TestPlan{2}.Source = 'Scenario.sldd';
            ConfigInfos.TestPlan{2}.Name = 'Swept Sine';
           ConfigInfos.TestPlan{2}.Cycle = 'Disabled';
          ConfigInfos.TestPlan{2}.Driver = 'Predictive Driver';
        ConfigInfos.TestPlan{2}.Data=[];

             ConfigInfos.TestPlan{3}.Num = 3;
          ConfigInfos.TestPlan{3}.Source = 'Scenario.sldd';
            ConfigInfos.TestPlan{3}.Name = 'Sine with Dwell';
           ConfigInfos.TestPlan{3}.Cycle = 'Disabled';
          ConfigInfos.TestPlan{3}.Driver = 'Predictive Driver';
        ConfigInfos.TestPlan{3}.Data=[];

             ConfigInfos.TestPlan{4}.Num = 4;
          ConfigInfos.TestPlan{4}.Source = 'Scenario.sldd';
            ConfigInfos.TestPlan{4}.Name = 'Fishhook';
           ConfigInfos.TestPlan{4}.Cycle = 'Disabled';
          ConfigInfos.TestPlan{4}.Driver = 'Predictive Driver';
        ConfigInfos.TestPlan{4}.Data=[];

             ConfigInfos.TestPlan{5}.Num = 5;
          ConfigInfos.TestPlan{5}.Source = 'Scenario.sldd';
            ConfigInfos.TestPlan{5}.Name = 'Double Lane Change';
           ConfigInfos.TestPlan{5}.Cycle = 'Disabled';
          ConfigInfos.TestPlan{5}.Driver = 'Predictive Stanley Driver';
        ConfigInfos.TestPlan{5}.Data=[];

             ConfigInfos.TestPlan{6}.Num = 6;
          ConfigInfos.TestPlan{6}.Source = 'Scenario.sldd';
            ConfigInfos.TestPlan{6}.Name = 'Constant Radius';
           ConfigInfos.TestPlan{6}.Cycle = 'Disabled';
          ConfigInfos.TestPlan{6}.Driver = 'Predictive Stanley Driver';
        ConfigInfos.TestPlan{6}.Data=[];

             ConfigInfos.TestPlan{7}.Num = 7;
          ConfigInfos.TestPlan{7}.Source = 'Scenario.sldd';
            ConfigInfos.TestPlan{7}.Name = 'Drive Cycle';
           ConfigInfos.TestPlan{7}.Cycle = 'FTP75';
          ConfigInfos.TestPlan{7}.Driver = 'Predictive Stanley Driver';
        ConfigInfos.TestPlan{7}.Data=[];

             ConfigInfos.TestPlan{8}.Num = 8;
          ConfigInfos.TestPlan{8}.Source = 'Scenario.sldd';
            ConfigInfos.TestPlan{8}.Name = 'Drive Cycle';
           ConfigInfos.TestPlan{8}.Cycle = 'FTP75';
          ConfigInfos.TestPlan{8}.Driver = 'Longitudinal Driver';
        ConfigInfos.TestPlan{8}.Data=[];

             ConfigInfos.TestPlan{9}.Num = 9;
          ConfigInfos.TestPlan{9}.Source = 'Scenario.sldd';
            ConfigInfos.TestPlan{9}.Name = 'Wide Open Throttle';
           ConfigInfos.TestPlan{9}.Cycle = 'Wide Open Throttle (WOT)';
          ConfigInfos.TestPlan{9}.Driver = 'Longitudinal Driver';
        ConfigInfos.TestPlan{9}.Data=[];

%% Selected Logging Signals
ConfigInfos.SelectedSignals = {
'Battery.BattInfo.BattCurr',...
'Battery.BattInfo.BattSoc',...
'Battery.BattInfo.BattVolt',...
'Body.BdyFrm.Cg.Acc.ax',...
'Body.BdyFrm.Cg.Acc.ay',...
'Body.BdyFrm.Cg.Acc.az',...
'Body.BdyFrm.Cg.AngVel.r',...
'Body.BdyFrm.Cg.Vel.xdot',...
'Body.BdyFrm.Cg.Vel.ydot',...
'Driver.AccelFdbk',...
'Driver.DecelFdbk',...
'Driver.GearFdbk',...
'Driver.SteerFdbk',...
'EM.EMSpd',...
'EM.EMTrq',...
'FrntWheels.Wheels.Alpha',...
'FrntWheels.Wheels.Fy',...
'FrntWheels.Wheels.Fz',...
'IMU.Acc',...
'IMU.pqr',...
'RearWheels.Wheels.Alpha',...
'RearWheels.Wheels.Fy',...
'RearWheels.Wheels.Fz',...
'Steering.Front.WhlAng.FL',...
'Steering.Front.WhlAng.FR',...
'Steering.Rear.WhlAng.RL',...
'Steering.Rear.WhlAng.RR',...
};

%% Finish
